### List products
GET http://localhost:8080/api/products
Accept: application/json


### Create product
POST http://localhost:8080/api/products
Content-Type: application/json
Accept: application/json

{
  "id": "550e8400-e29b-41d4-a716-446655440000",
  "name": "Arroz",
  "description": "Paquete de arroz blanco",
  "measurementUnit": "kg",
  "actualStock": 100
}


### Show product
GET http://localhost:8080/api/products/550e8400-e29b-41d4-a716-446655440000
Accept: application/json


### Update full product with PUT
PUT http://localhost:8080/api/products/550e8400-e29b-41d4-a716-446655440000
Content-Type: application/json
Accept: application/json

{
  "name": "Arroz integral",
  "description": "Paquete de arroz integral de 1 kg",
  "measurementUnit": "kg",
  "actualStock": 80
}


### Delete product
DELETE http://localhost:8080/api/products/550e8400-e29b-41d4-a716-446655440000
Accept: application/json


### Show deleted product
GET http://localhost:8080/api/products/550e8400-e29b-41d4-a716-446655440000
Accept: application/json